In [ ]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
dataTest = pd.read_csv("dataFlight.csv", sep=',')

data=(dataTest[dataTest['Year']>2002])

data[['SecurityDelay','CarrierDelay','WeatherDelay','NASDelay','LateAircraftDelay','DepDelayMinutes']] = data[['SecurityDelay','CarrierDelay','WeatherDelay','NASDelay','LateAircraftDelay','DepDelayMinutes']].fillna(value=0)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
data.shape

df = data.loc[:, ['Year','Quarter','Month', 'DayofMonth', 'DayOfWeek', 'FlightDate', 'Reporting_Airline', 'Flight_Number_Reporting_Airline',
'Origin', 'OriginCityName', 'OriginState', 'OriginStateName', 'Dest', 'DestCityName', 'DestState', 'DestStateName', 'DestWac',
'CRSDepTime', 'DepTime', 'DepDelayMinutes', 'CRSArrTime', 'ArrTime', 'ArrDelayMinutes', 'Cancelled',  
'Diverted', 'Flights', 'Distance', 'DistanceGroup', 'CarrierDelay', 'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay']]
df.head()

df.to_csv('DataFlightFinal.csv', index=False)

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,Flight_Number_Reporting_Airline,Origin,OriginCityName,OriginState,OriginStateName,Dest,DestCityName,DestState,DestStateName,DestWac,CRSDepTime,DepTime,DepDelayMinutes,TaxiOut,CRSArrTime,ArrTime,ArrDelayMinutes,Cancelled,Diverted,Flights,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
4,2006,1,1,15,7,2006-01-15,US,465,EWR,"Newark, NJ",NJ,New Jersey,CLT,"Charlotte, NC",NC,North Carolina,36,1820,1911.0,51.0,19.0,2026,2058.0,32.0,0.0,0.0,1.0,529.0,3,0.0,0.0,0.0,0.0,32.0
7,2019,2,6,11,2,2019-06-11,9E,3459,ATL,"Atlanta, GA",GA,Georgia,CAE,"Columbia, SC",SC,South Carolina,37,1950,2331.0,221.0,19.0,2057,31.0,214.0,0.0,0.0,1.0,192.0,1,0.0,0.0,0.0,0.0,214.0
9,2018,1,2,8,4,2018-02-08,WN,5932,MDW,"Chicago, IL",IL,Illinois,DAL,"Dallas, TX",TX,Texas,74,2030,2046.0,16.0,34.0,2250,2319.0,29.0,0.0,0.0,1.0,793.0,4,0.0,0.0,13.0,0.0,16.0
23,2020,1,3,24,2,2020-03-24,YV,5825,PHX,"Phoenix, AZ",AZ,Arizona,LGB,"Long Beach, CA",CA,California,91,1858,1950.0,52.0,9.0,2021,2105.0,44.0,0.0,0.0,1.0,355.0,2,44.0,0.0,0.0,0.0,0.0
24,2010,3,8,20,5,2010-08-20,OO,6582,BUR,"Burbank, CA",CA,California,SFO,"San Francisco, CA",CA,California,91,1342,1352.0,10.0,20.0,1453,1510.0,17.0,0.0,0.0,1.0,326.0,2,9.0,0.0,7.0,0.0,1.0

In [17]:
df.to_csv('DataFlightFinal.csv', index=False)

In [22]:
dataTest["Reporting_Airline"].unique().shape

(33,)

In [ ]:
# Convert the date column to datetime format
df['FlightDate'] = pd.to_datetime(df['FlightDate'], format='%y-%m-%d')

# Sort the DataFrame by date
df = df.sort_values('FlightDate', ascending=True)

In [30]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
column_list = list(dataTest.columns)

# print the list of column names
print(len(column_list))
df_filtered = dataTest[dataTest["ArrDelayMinutes"] == 0]

ValueError: time data '2006-01-15' does not match format '%y-%m-%d' (match)